config/routes.rb
First::Application.routes.draw do

  devise_scope :user do
    authenticated :user do
    	root :to => 'users#index', as: :authenticated_root
    end
    unauthenticated :user do
	root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end
  scope 'settings' do
    resource :profile, :only=>[:show,:update]
    as :user do
      get 'account'=>'devise/registrations#edit',:as=>'account'
    end
  end

  devise_for :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_filter :configure_permitted_parameters,if: :devise_controller?











  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:username,:email,:password,:password_confirmation)}
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
  end

  def show
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def creat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_header.html.erb
<%if user_signed_in?%>
      <header class="nav navbar-fixed-top navbar-inverse">
	<div class="container">
	  <ul class="nav navbar-nav  pull-right">
	    <li><%=link_to current_user.username,authenticated_root_path%></li>
	    <li><%=link_to"个人设置", account_path%></li>
	    <li><%=link_to" 退 出", destroy_user_session_path, method: "delete"%></li>
	    <li><span class="glyphicon glyphicon-home"></span></li>	
          </ul> 
	</div>
      </header>
<%end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>First</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(resource.errors.count, "error") %>.
    </div>
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics#index</h1>
<p>Find me in app/views/topics/index.html.erb</p>

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>

app/views/users/creat.html.erb
<h1>Users#creat</h1>
<p>Find me in app/views/users/creat.html.erb</p>

app/views/users/index.html.erb
<div id="content">
<div class="container">
  <ul class="nav pull-center  nav-tabs">
    <li class="active"><%=link_to"最新动态","#"%></li>
    <li><%=link_to"我参与的投票","#"%></li>
    <li><%=link_to"自己发起的投票","#"%></li>
  </ul>
</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>